events {}

http {
  resolver 127.0.0.11 valid=5s;

  server {
    listen 80;
    server_name api.nishantdd.dev;

    return 301 https://$host$request_uri;
  }

  upstream backend {
    server app-green:8080;
  }
  server {
    listen 443 ssl;
    server_name api.nishantdd.dev;

    ssl_certificate /etc/nginx/ssl/live/api.nishantdd.dev/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/api.nishantdd.dev/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {

      proxy_pass http://backend;

      proxy_connect_timeout 2s;
      proxy_read_timeout 5s;

      proxy_next_upstream error timeout http_502 http_503 http_504;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}